spring:
  flyway:
    baseline-on-migrate: true
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/yugioh?serverTimezone=UTC&useSSL=false
    username: postgres
    password: 1010100
  application:
    name: service-core
  devtools:
    livereload:
      enabled: true
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
